// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvDU8dg1nW2Hzl2phW35JTxfaHhESWvcY',
    appId: '1:607365899761:android:3a230a83bdf00cf8df9050',
    messagingSenderId: '607365899761',
    projectId: 'udemyfluttercompleteguide',
    databaseURL: 'https://udemyfluttercompleteguide-default-rtdb.firebaseio.com',
    storageBucket: 'udemyfluttercompleteguide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw6jGQXZegL7dpZOZQobSEe8UO5WXqmdI',
    appId: '1:607365899761:ios:ff1b7b169dcf1705df9050',
    messagingSenderId: '607365899761',
    projectId: 'udemyfluttercompleteguide',
    databaseURL: 'https://udemyfluttercompleteguide-default-rtdb.firebaseio.com',
    storageBucket: 'udemyfluttercompleteguide.firebasestorage.app',
    iosBundleId: 'com.udemy.flutter.dart.section14',
  );
}
